version: 2
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-10.6.0-browsers
    working_directory: ~/UnitJS
    steps:
      - checkout
      - run:
          name: Update npm
          command: sudo npm install -g npm@6.5.0
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Test UnitJS source
          command: npm run test
      - run:
          name: Run GCC build
          command: npm run build
      - run:
          name: Test UnitJS build
          command: npm run test:build
