version: 2
jobs:
  build:
    working_directory: ~/UNIT
    docker:
      - image: circleci/node:chakracore-10.6.0-browsers
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: 'npm install'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run ESLint
          command: 'npm run lint'
      - run:
          name: Run Karma tests
          command: 'npm run test'