version: 2
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-10.6.0-browsers
    working_directory: ~/UnitJS
    steps:
      - checkout
      - run:
          name: Update Node.js and npm
          command: |
            curl -sSL "https://nodejs.org/dist/v14.17.0/node-v14.17.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v14.17.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Test UnitJS source
          command: npm run test
      - run:
          name: Run GCC build
          command: npm run build:min
